# Generated by Django 5.1.4 on 2025-01-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date', models.DateField()),
                ('disciplinery_status', models.CharField(choices=[('very_good', 'Very Good'), ('good', 'Good'), ('normal', 'Normal'), ('bad', 'Bad')], max_length=255)),
            ],
        ),
    ]
