# Generated by Django 5.1.4 on 2025-01-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(max_length=20),
        ),
    ]
