# Generated by Django 5.1.4 on 2025-01-16 17:46

import builtins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuptoevent',
            name='student',
        ),
        migrations.AddField(
            model_name='signuptoevent',
            name='user',
            field=models.ForeignKey(default=builtins.print, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
