# Generated by Django 5.1.4 on 2025-01-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_signuptoevent_student_signuptoevent_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpToEvent',
        ),
    ]
