# Generated by Django 5.1.4 on 2025-01-06 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=50)),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('address', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_room.classroom')),
            ],
        ),
    ]
