# Generated by Django 5.1.4 on 2025-01-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(choices=[('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10)),
                ('field', models.CharField(choices=[('computer', 'Computer'), ('electronic', 'Electronic'), ('mechanic', 'Mechanic')], max_length=255)),
            ],
        ),
    ]
